name: j_manim
channels:
  - defaults
dependencies:
  - ffmpeg
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - argon2-cffi=20.1.0=py39h27cfd23_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=3.3.1=pyhd3eb1b0_0
  - ca-certificates=2021.7.5=h06a4308_1
  - cairo=1.16.0=hf32fb01_1
  - certifi=2021.5.30=py39h06a4308_0
  - cffi=1.14.6=py39h400218f_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py39h06a4308_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.69.0=h5202010_0
  - icu=58.2=he6710b0_3
  - importlib-metadata=3.10.0=py39h06a4308_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - ipykernel=5.3.4=py39hb070fc8_0
  - ipython=7.22.0=py39hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.2=py39h06a4308_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - markupsafe=2.0.1=py39h27cfd23_0
  - mistune=0.8.4=py39h27cfd23_1000
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py39h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.0=py39h06a4308_0
  - openssl=1.1.1k=h27cfd23_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py39h06a4308_1
  - parso=0.7.0=py_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.1.3=py39h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycairo=1.19.1=py39h708ec4a_0
  - pycparser=2.20=py_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py39h7f8727e_0
  - python=3.9.6=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=20.0.0=py39h2531618_1
  - readline=8.1=h27cfd23_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - terminado=0.9.4=py39h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py39h27cfd23_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - tzdata=2021a=h52ac0ba_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py39h06a4308_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - argparse==1.4.0
    - colour==0.1.5
    - jupyter-manim==1.3
    - manimlib==0.2.0
    - numpy==1.21.1
    - opencv-python==4.5.3.56
    - pillow==8.3.1
    - progressbar==2.5
    - pydub==0.25.1
    - scipy==1.7.0
    - tqdm==4.62.0
